project:
  type: manuscript
  execute-dir: project

bibliography: bibliography.bib

manuscript:
  article: main.qmd

format:
  pdf: 
    documentclass: article
    link-citations: true
    suppress-bibliography: true
    keep-tex: false
    geometry: 
      - left=1in
      - right=1in
      
execute:
  freeze: true



